[package]
name = "rollshot-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "rollshot-app"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
image = { workspace = true }
rfd = "0.15"
rollshot-capture = { path = "../rollshot-capture" }
rollshot-iced-overlay = { path = "../rollshot-iced-overlay" }
serde_json = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
