//! Fixed FFmpeg render graph compilation.
//!
//! Compiles a deterministic FFmpeg filter graph from a validated plan.
//! Labels are generated by shot index only. All text is already rasterized
//! into PNG overlays. No user/model strings enter the graph.

use std::ffi::{OsStr, OsString};
use std::path::Path;

use super::error::LaunchTeaserRenderError;
use super::overlay::OverlayAsset;
use super::plan::{
    ValidatedLaunchTeaserPlan, FINAL_FPS, FINAL_HEIGHT, FINAL_WIDTH, PREVIEW_HEIGHT, PREVIEW_WIDTH,
};

/// Render output profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenderProfile {
    /// Full-resolution final output (1920x1080).
    Final,
    /// Half-resolution preview (960x540).
    Preview,
}

impl RenderProfile {
    /// Output width for this profile.
    pub fn width(&self) -> u32 {
        match self {
            Self::Final => FINAL_WIDTH,
            Self::Preview => PREVIEW_WIDTH,
        }
    }

    /// Output height for this profile.
    pub fn height(&self) -> u32 {
        match self {
            Self::Final => FINAL_HEIGHT,
            Self::Preview => PREVIEW_HEIGHT,
        }
    }
}

/// A compiled FFmpeg graph ready for process spawn.
#[derive(Debug, Clone)]
pub struct CompiledLaunchTeaserGraph {
    args: Vec<OsString>,
}

impl CompiledLaunchTeaserGraph {
    /// The full argument list for FFmpeg invocation.
    pub fn args(&self) -> &[OsString] {
        &self.args
    }
}

/// Compile the fixed FFmpeg render graph.
///
/// The filter graph is written to a scratch file and passed as an argument.
/// No user/model text enters the graph because all text is already rasterized.
pub fn compile_ffmpeg_graph(
    plan: &ValidatedLaunchTeaserPlan,
    motion_path: &Path,
    overlays: &[OverlayAsset],
    output_path: &Path,
    profile: RenderProfile,
    scratch: &Path,
) -> Result<CompiledLaunchTeaserGraph, LaunchTeaserRenderError> {
    let plan_inner = plan.plan();
    let shot_count = plan_inner.shots.len();
    let out_w = profile.width();
    let out_h = profile.height();

    // Build the filter graph.
    let mut filters = Vec::new();

    // For each shot: trim, setpts, crop (focus interpolation), scale+pad.
    for (i, shot) in plan_inner.shots.iter().enumerate() {
        let start_pts = shot.source_start_ms as f64 / 1_000.0;
        let end_pts = shot.source_end_ms as f64 / 1_000.0;

        // Trim and reset PTS.
        filters.push(format!(
            "[0:v]trim=start={start_pts}:end={end_pts},setpts=PTS-STARTPTS[trim{i}]"
        ));

        // Focus crop: interpolate center from start to end.
        // Source dimensions are used for crop geometry.
        let src_w = plan_inner.source.motion_width;
        let src_h = plan_inner.source.motion_height;

        // Compute crop size based on zoom.
        let zoom = shot.focus_path.zoom_permille as f64 / 1_000.0;
        let crop_w = ((src_w as f64) / zoom) as u32;
        let crop_h = ((src_h as f64) / zoom) as u32;

        // Compute crop position from normalized focus points (0-10000).
        // Center: start and end are the same for default plans.
        let cx_start = (shot.focus_path.start.x as f64 / 10_000.0) * src_w as f64;
        let cy_start = (shot.focus_path.start.y as f64 / 10_000.0) * src_h as f64;
        let cx_end = (shot.focus_path.end.x as f64 / 10_000.0) * src_w as f64;
        let cy_end = (shot.focus_path.end.y as f64 / 10_000.0) * src_h as f64;

        let displayed_dur_ms = shot.displayed_ms();
        let displayed_dur_s = displayed_dur_ms as f64 / 1_000.0;

        // Interpolated crop position.
        let crop_x_expr = format!("'({cx_start})+(({cx_end})-({cx_start}))*t/{displayed_dur_s}'");
        let crop_y_expr = format!("'({cy_start})+(({cy_end})-({cy_start}))*t/{displayed_dur_s}'");

        // Clamp crop to stay within source bounds.
        let crop_x_expr = format!("'min(max({crop_x_expr}-({crop_w}/2),0),{src_w}-{crop_w})'");
        let crop_y_expr = format!("'min(max({crop_y_expr}-({crop_h}/2),0),{src_h}-{crop_h})'");

        filters.push(format!(
            "[trim{i}]crop={crop_w}:{crop_h}:{crop_x_expr}:{crop_y_expr}[crop{i}]"
        ));

        // Scale and pad to output dimensions.
        filters.push(format!(
            "[crop{i}]scale={out_w}:{out_h}:force_original_aspect_ratio=decrease,pad={out_w}:{out_h}:(ow-iw)/2:(oh-ih)/2[scaled{i}]"
        ));

        // Apply ALL overlays for this shot, chained sequentially.
        // Shot 0 may have hook + caption; final shot may have caption + outro.
        let shot_overlays: Vec<&OverlayAsset> =
            overlays.iter().filter(|o| o.shot_index == i).collect();
        for (k, overlay) in shot_overlays.iter().enumerate() {
            let overlay_path = overlay.path.to_string_lossy();
            let input = if k == 0 {
                format!("[scaled{i}]")
            } else {
                let prev = k - 1;
                format!("[ovr{i}_{prev}]")
            };
            let output = if k == shot_overlays.len() - 1 {
                format!("[shot{i}]")
            } else {
                format!("[ovr{i}_{k}]")
            };
            filters.push(format!(
                "movie={overlay_path}[ovr{i}_{k}];{input}[ovr{i}_{k}]overlay=0:0{output}"
            ));
        }
    }

    // Concatenate shots. Determine the final label per shot.
    let mut concat_inputs = String::new();
    let mut shot_labels = Vec::new();
    for i in 0..shot_count {
        let has_overlay = overlays.iter().any(|o| o.shot_index == i);
        let label = if has_overlay {
            format!("[shot{i}]")
        } else {
            format!("[scaled{i}]")
        };
        concat_inputs.push_str(&label);
        shot_labels.push(label);
    }

    // Check for crossfades between adjacent shots.
    let has_any_crossfade = plan_inner
        .shots
        .iter()
        .any(|s| matches!(s.transition, super::plan::TransitionV1::Crossfade { .. }));

    if has_any_crossfade {
        // Use xfade chain for crossfade transitions.
        let mut current = shot_labels[0].clone();
        for (i, shot) in plan_inner.shots.iter().enumerate().skip(1) {
            if let super::plan::TransitionV1::Crossfade { duration_ms } = shot.transition {
                let offset_s = plan_inner.cumulative_start_ms(i) as f64 / 1_000.0
                    - (duration_ms as f64 / 1_000.0);
                let next = if i == shot_count - 1 {
                    "[outv]".to_string()
                } else {
                    format!("[xfade{i}]")
                };
                filters.push(format!(
                    "{current}{next_input}xfade=transition=fade:duration={dur}:offset={offset}{next}",
                    next_input = shot_labels[i],
                    dur = duration_ms as f64 / 1_000.0,
                    offset = offset_s.max(0.0),
                ));
                current = next;
            } else {
                // Cut: concat current + this shot, then continue.
                let next = if i == shot_count - 1 {
                    "[outv]".to_string()
                } else {
                    format!("[xfade{i}]")
                };
                filters.push(format!(
                    "{current}{label}concat=n=2:v=1:a=0{next}",
                    label = shot_labels[i],
                ));
                current = next;
            }
        }
    } else {
        // Simple concat for all-cut transitions.
        filters.push(format!(
            "{concat_inputs}concat=n={shot_count}:v=1:a=0[outv]"
        ));
    }

    let filter_graph = filters.join(";\n");

    // Write filter graph to a scratch file.
    let filter_path = scratch.join("filter.txt");
    std::fs::write(&filter_path, &filter_graph)
        .map_err(|_| LaunchTeaserRenderError::GraphCompilationFailed)?;

    // Build FFmpeg arguments.
    let mut args: Vec<OsString> = vec![
        OsStr::new("-y").into(),
        OsStr::new("-nostdin").into(),
        OsStr::new("-i").into(),
        motion_path.into(),
        OsStr::new("-filter_complex_script").into(),
        filter_path.into(),
    ];

    // Map the final output label.
    args.push(OsStr::new("-map").into());
    args.push(OsStr::new("[outv]").into());

    // Video codec settings.
    args.push(OsStr::new("-c:v").into());
    args.push(OsStr::new("libx264").into());
    args.push(OsStr::new("-pix_fmt").into());
    args.push(OsStr::new("yuv420p").into());
    args.push(OsStr::new("-r").into());
    args.push(OsStr::new(&FINAL_FPS.to_string()).into());

    // No audio.
    args.push(OsStr::new("-an").into());

    // Output path.
    args.push(output_path.into());

    Ok(CompiledLaunchTeaserGraph { args })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::launch_teaser::overlay::prepare_overlay_assets;
    use crate::launch_teaser::plan::*;
    use crate::project::ProjectStepId;

    fn valid_plan() -> LaunchTeaserPlanV1 {
        LaunchTeaserPlanV1 {
            schema_version: LAUNCH_TEASER_SCHEMA_VERSION,
            source: LaunchTeaserSourceV1 {
                project_revision: 1,
                projection_digest: "a".repeat(64),
                motion_sha256: "b".repeat(64),
                motion_duration_ms: 30_000,
                motion_width: 1920,
                motion_height: 1080,
            },
            hook: "Test Hook".into(),
            shots: vec![
                LaunchTeaserShotV1 {
                    reviewed_step_id: ProjectStepId(1),
                    source_start_ms: 0,
                    source_end_ms: 5_000,
                    focus_path: FocusPathV1 {
                        start: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        end: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        zoom_permille: 1_000,
                    },
                    speed: SpeedV1::P1000,
                    caption: "First step".into(),
                    transition: TransitionV1::Cut,
                },
                LaunchTeaserShotV1 {
                    reviewed_step_id: ProjectStepId(2),
                    source_start_ms: 5_000,
                    source_end_ms: 10_000,
                    focus_path: FocusPathV1 {
                        start: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        end: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        zoom_permille: 1_000,
                    },
                    speed: SpeedV1::P1000,
                    caption: "Second step".into(),
                    transition: TransitionV1::Cut,
                },
                LaunchTeaserShotV1 {
                    reviewed_step_id: ProjectStepId(3),
                    source_start_ms: 10_000,
                    source_end_ms: 15_000,
                    focus_path: FocusPathV1 {
                        start: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        end: NormalizedPointV1 { x: 5_000, y: 5_000 },
                        zoom_permille: 1_000,
                    },
                    speed: SpeedV1::P1000,
                    caption: "Third step".into(),
                    transition: TransitionV1::Cut,
                },
            ],
            outro_text: "Made with Rollshot".into(),
            provenance: LaunchTeaserProvenanceV1 {
                deterministic_seed_version: 1,
                agent: None,
                repository_reads: Vec::new(),
                accepted_user_edits: Vec::new(),
            },
        }
    }

    #[test]
    fn hostile_caption_never_enters_ffmpeg_arguments() {
        let mut plan = valid_plan();
        plan.shots[0].caption = "x'];movie=/etc/passwd['y".into();
        let validated = plan.validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets =
            prepare_overlay_assets(&validated, scratch.path(), RenderProfile::Final).unwrap();
        let motion_path = Path::new("/tmp/fake.mp4");
        let output_path = tempfile::tempdir().unwrap().path().join("out.mp4");
        let graph = compile_ffmpeg_graph(
            &validated,
            motion_path,
            &assets,
            &output_path,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let joined: String = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(!joined.contains("/etc/passwd"));
        // Text content only appears in overlay PNG paths, not in filter expressions.
        assert!(!joined.contains("x']"));
    }

    #[test]
    fn graph_uses_profile_dimensions() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();
        assert!(filter.contains(&format!("{FINAL_WIDTH}")));
        assert!(filter.contains(&format!("{FINAL_HEIGHT}")));
    }

    #[test]
    fn preview_graph_uses_smaller_dimensions() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Preview).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Preview,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();
        assert!(filter.contains(&format!("{PREVIEW_WIDTH}")));
        assert!(filter.contains(&format!("{PREVIEW_HEIGHT}")));
    }

    #[test]
    fn graph_contains_no_audio_mapping() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let args: Vec<String> = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(args.contains(&"-an".to_string()));
    }

    #[test]
    fn graph_uses_h264_codec() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let args: Vec<String> = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(args.contains(&"libx264".to_string()));
        assert!(args.contains(&"yuv420p".to_string()));
    }

    #[test]
    fn graph_uses_30fps() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let args: Vec<String> = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(args.contains(&"30".to_string()));
    }

    #[test]
    fn filter_graph_written_to_scratch_file() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter_path = scratch.path().join("filter.txt");
        assert!(filter_path.is_file());
        let filter = std::fs::read_to_string(&filter_path).unwrap();
        assert!(filter.contains("trim"));
        assert!(filter.contains("crop"));
        assert!(filter.contains("concat"));
    }

    #[test]
    fn graph_args_contain_nostdin() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let args: Vec<String> = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(args.contains(&"-nostdin".to_string()));
    }

    #[test]
    fn graph_args_contain_filter_complex_script() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let args: Vec<String> = graph
            .args()
            .iter()
            .map(|s| s.to_string_lossy().to_string())
            .collect();
        assert!(args.contains(&"-filter_complex_script".to_string()));
    }

    #[test]
    fn crossfade_plan_generates_xfade_filter() {
        let mut plan = valid_plan();
        plan.shots[1].transition = TransitionV1::Crossfade { duration_ms: 500 };
        plan.shots[0].source_end_ms = 5_500;
        plan.shots[1].source_start_ms = 5_500;
        plan.shots[1].source_end_ms = 11_000;
        plan.shots[2].source_start_ms = 11_000;
        plan.shots[2].source_end_ms = 16_500;
        plan.source.motion_duration_ms = 16_500;
        let validated = plan.validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets =
            prepare_overlay_assets(&validated, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &validated,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();
        assert!(filter.contains("xfade"));
    }

    #[test]
    fn shot0_filter_contains_both_hook_and_caption_overlay() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();
        // Shot 0 has hook + caption = two overlays chained.
        let shot0_overlays: Vec<_> = assets.iter().filter(|a| a.shot_index == 0).collect();
        assert_eq!(
            shot0_overlays.len(),
            2,
            "expected hook + caption for shot 0"
        );
        // Both overlay files must appear in the filter graph.
        for overlay in &shot0_overlays {
            let fname = overlay.path.file_name().unwrap().to_string_lossy();
            assert!(
                filter.contains(&*fname),
                "filter graph missing overlay reference: {fname}"
            );
        }
        // The chain must produce a [shot0] label.
        assert!(filter.contains("[shot0]"));
    }

    #[test]
    fn shot2_filter_contains_both_caption_and_outro_overlay() {
        let plan = valid_plan().validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets = prepare_overlay_assets(&plan, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &plan,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();
        // Shot 2 has caption + outro = two overlays chained.
        let shot2_overlays: Vec<_> = assets.iter().filter(|a| a.shot_index == 2).collect();
        assert_eq!(
            shot2_overlays.len(),
            2,
            "expected caption + outro for shot 2"
        );
        for overlay in &shot2_overlays {
            let fname = overlay.path.file_name().unwrap().to_string_lossy();
            assert!(
                filter.contains(&*fname),
                "filter graph missing overlay reference: {fname}"
            );
        }
        assert!(filter.contains("[shot2]"));
    }

    /// I-4: Validate the filter graph for a mixed Cut+Crossfade+Cut transition plan.
    /// Ensures xfade offset is correct when Cut follows Crossfade and final output
    /// label is [outv].
    #[test]
    fn mixed_cut_crossfade_cut_generates_correct_filter_graph() {
        let mut plan = valid_plan();
        // Shot 0: Cut (default)
        // Shot 1: Crossfade 500ms
        plan.shots[1].transition = TransitionV1::Crossfade { duration_ms: 500 };
        // Shot 2: Cut (default)
        // Extend source ranges so the plan still validates.
        plan.shots[0].source_end_ms = 5_500;
        plan.shots[1].source_start_ms = 5_500;
        plan.shots[1].source_end_ms = 11_000;
        plan.shots[2].source_start_ms = 11_000;
        plan.shots[2].source_end_ms = 16_500;
        plan.source.motion_duration_ms = 16_500;

        let validated = plan.validate().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let assets =
            prepare_overlay_assets(&validated, scratch.path(), RenderProfile::Final).unwrap();
        let motion = Path::new("/tmp/fake.mp4");
        let output = Path::new("/tmp/out.mp4");
        let _graph = compile_ffmpeg_graph(
            &validated,
            motion,
            &assets,
            output,
            RenderProfile::Final,
            scratch.path(),
        )
        .unwrap();
        let filter = std::fs::read_to_string(scratch.path().join("filter.txt")).unwrap();

        // Must contain an xfade filter for the crossfade transition.
        assert!(
            filter.contains("xfade"),
            "mixed plan must use xfade for crossfade transition"
        );

        // Must contain a concat filter for the Cut transition within the xfade chain.
        assert!(
            filter.contains("concat"),
            "mixed plan must use concat for cut transition within xfade chain"
        );

        // The xfade offset for shot 1 (Crossfade 500ms) must be:
        // cumulative_start_ms(1) - 500ms = 5_500 - 500 = 5_000ms = 5.0s.
        // (shot 0 displayed = 5_500ms, no overlap since shot 0 is Cut)
        assert!(
            filter.contains("offset=5"),
            "xfade offset must be 5.0s for crossfade after cut, got: {filter}"
        );

        // Final output label must be [outv].
        assert!(
            filter.contains("[outv]"),
            "filter graph must end with [outv] label, got: {filter}"
        );
    }
}
